const BOT_PATTERNS = [
  "googlebot",
  "bingbot",
  "slurp",
  "duckduckbot",
  "baiduspider",
  "yandexbot",
  "facebookexternalhit",
  "facebot",
  "twitterbot",
  "linkedinbot",
  "pinterestbot",
  "slackbot",
  "discordbot",
  "telegrambot",
  "whatsapp",
  "applebot",
  "aws-lambda",
  "cloudflare",
  "pingdom",
  "uptimerobot",
  "semrushbot",
  "ahrefsbot",
  "majestic",
  "rogerbot",
  "dotbot",
  "blexbot",
  "exabot",
  "fastbot",
  "ia_archiver",
  "spider",
  "crawler",
  "scraper",
];

export const isBot = (userAgent: string): boolean =>
  BOT_PATTERNS.some((pattern) => userAgent.includes(pattern));
